### ISSUE TITLE
when i start py main.py its show me this please tell me how can i fix this

### ISSUE THREAD

**Issue by 13Zorawar** [GREENFONTS/keylogger#1]

**Comment by 13Zorawar** [comment]
Traceback (most recent call last):
  File "/home/kali/Desktop/Tools/keylogger/main.py", line 2, in <module>
    from pynput.keyboard import Listener, Key
  File "/usr/local/lib/python3.10/dist-packages/pynput-1.7.6-py3.10.egg/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/usr/local/lib/python3.10/dist-packages/pynput-1.7.6-py3.10.egg/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/usr/local/lib/python3.10/dist-packages/pynput-1.7.6-py3.10.egg/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":1": b\'No protocol specified\\n\'', DisplayConnectionError(':1', b'No protocol specified\n'))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly

**Comment by GREENFONTS** [comment]
Please, what operating system are you using.

**Comment by 13Zorawar** [comment]
> Please, what operating system are you using.

kali linux bro u have discord brother ?

i want to learn so many things in this field i need someone who can guide me

**Comment by GREENFONTS** [comment]
Yeaa...I have discord

It's from your operating system..

You have to run the script as root
Check this for reference:
https://pynput.readthedocs.io/en/latest/limitations.html
